- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
