- name: Install firefox
  community.general.snap:
    name: firefox
  async: 300
  poll: 0
  register: install_firefox_job

- name: Install python3-venv
  ansible.builtin.apt:
    name:
      - python3-venv
      - python3-pip
    update_cache: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: true
  async: 300
  poll: 0

- name: Create src directory
  ansible.builtin.file:
    path: "/home/{{ prob_user | default(ansible_user, true) }}/src"
    state: directory
    owner: "{{ prob_user | default(ansible_user, true) }}"
    group: "{{ prob_user | default(ansible_user, true) }}"
    mode: "0755"

- name: Wait for firefox installation to complete
  ansible.builtin.async_status:
    jid: "{{ install_firefox_job.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 5

- name: Find geckodriver path
  ansible.builtin.shell: |
    which geckodriver
  register: geckodriver_path
  changed_when: false
  failed_when: geckodriver_path.rc != 0

- name: Copy firefox.py
  ansible.builtin.template:
    src: src/firefox.py.j2
    dest: "/home/{{ prob_user | default(ansible_user, true) }}/src/firefox.py"
    owner: "{{ prob_user | default(ansible_user, true) }}"
    group: "{{ prob_user | default(ansible_user, true) }}"
    mode: "0664"

- name: Install selenium (venv)
  become: true
  become_user: "{{ prob_user | default(ansible_user, true) }}"
  ansible.builtin.pip:
    name: selenium
    virtualenv: "/home/{{ prob_user | default(ansible_user, true) }}/src/.venv"
    virtualenv_command: "{{ discovered_interpreter_python }} -m venv"

- name: Setup cron to run firefox.py every 3 minutes
  ansible.builtin.cron:
    name: run firefox.py
    user: "{{ prob_user | default(ansible_user, true) }}"
    minute: "*/3"
    job: "/home/{{ prob_user | default(ansible_user, true) }}/src/.venv/bin/python /home/{{ prob_user | default(ansible_user, true) }}/src/firefox.py"

- name: Generate netplan configuration
  ansible.builtin.template:
    src: netplan/10-config.yaml.j2
    dest: /etc/netplan/10-config.yaml
    owner: root
    group: root
    mode: "0600"
  notify: Apply netplan
