- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - wget
    update_cache: true

- name: Add CZ.NIC Labs Packaging GPG key
  ansible.builtin.get_url:
    url: https://pkg.labs.nic.cz/gpg
    dest: /usr/share/keyrings/cznic-labs-pkg.gpg
    mode: "0644"
  notify: Restart Knot DNS

- name: Setup the knot-dns repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cznic-labs-pkg.gpg] https://pkg.labs.nic.cz/knot-dns {{ ansible_distribution_release }} main"
    filename: cznic-labs-knot-dns
    state: present
    update_cache: true
  notify: Restart Knot DNS

- name: Install Knot DNS
  ansible.builtin.apt:
    name:
      - knot
  notify: Restart Knot DNS

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: true
  async: 300
  poll: 0

- name: Copy configuration and zone files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: knot
    mode: "0640"
  loop:
    - src: "knot/knot.conf.j2"
      dest: "/etc/knot/knot.conf"
    - src: "knot/internal.ikm.zone.j2"
      dest: "/var/lib/knot/internal.ikm.zone"
  notify: Restart Knot DNS

- name: Copy dns UFW rules
  ansible.builtin.copy:
    src: ufw/dns
    dest: /etc/ufw/applications.d/
    owner: root
    group: root
    mode: "0644"

- name: Allow SSH UFW
  community.general.ufw:
    rule: allow
    app: OpenSSH

- name: Allow DNS UFW
  community.general.ufw:
    rule: allow
    app: DNS

- name: Enable UFW
  community.general.ufw:
    default: deny
    state: enabled
