- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
    update_cache: true

- name: Download nginx signing key
  ansible.builtin.get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /tmp/nginx_signing.key
    mode: "0644"
  notify: Restart nginx

- name: Convert nginx signing key to gpg
  ansible.builtin.shell: |
    set -o pipefail
    gpg --dearmor -o /usr/share/keyrings/nginx-archive-keyring.gpg /tmp/nginx_signing.key
  args:
    creates: /usr/share/keyrings/nginx-archive-keyring.gpg
    executable: /bin/bash
  notify: Restart nginx

- name: Setup the nginx repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"
    filename: nginx
    state: present
    update_cache: true
  notify: Restart nginx

- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
  notify: Restart nginx

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: true
  async: 300
  poll: 0

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx

- name: Copy html file
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - src: nginx/index.html
      dest: /usr/share/nginx/html/
  notify: Restart nginx

- name: Create ssl directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: "0755"
  notify: Restart nginx

- name: Generate server private key
  ansible.builtin.shell: |
    openssl genrsa -out /etc/nginx/ssl/server.key 2048
  args:
    creates: /etc/nginx/ssl/server.key
  notify: Restart nginx

- name: Generate certificate signing request (CSR)
  ansible.builtin.shell: |
    openssl req -new -key /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.csr -subj "/C=JP/ST=Tokyo/L=Chofu/O=ICTSC/OU=ICTSC2024/CN=www.ikm.internal"
  args:
    creates: /etc/nginx/ssl/server.csr
  notify: Restart nginx

- name: Generate self-signed certificate
  ansible.builtin.shell: |
    openssl x509 -days 3650 -req -signkey /etc/nginx/ssl/server.key -in /etc/nginx/ssl/server.csr -out /etc/nginx/ssl/server.crt
  args:
    creates: /etc/nginx/ssl/server.crt
  notify: Restart nginx

- name: SSH deny prob_user login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers {{ prob_user }}"
    state: present
  notify: Restart ssh
  when: prob_user and prob_user != ansible_user # None, ""を除外
