- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - wget
    update_cache: true

- name: Add CZ.NIC Labs Packaging GPG key
  ansible.builtin.get_url:
    url: https://pkg.labs.nic.cz/gpg
    dest: /usr/share/keyrings/cznic-labs-pkg.gpg
    mode: "0644"
  notify: Start Knot Resolver

- name: Setup the knot-resolver repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cznic-labs-pkg.gpg] https://pkg.labs.nic.cz/knot-resolver {{ ansible_distribution_release }} main"
    filename: cznic-labs-knot-resolver
    state: present
    update_cache: true
  notify: Start Knot Resolver

- name: Install Knot Resolver
  ansible.builtin.apt:
    name:
      - knot-resolver
  notify: Start Knot Resolver

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: true
  async: 300
  poll: 0

- name: Copy kresd.conf
  ansible.builtin.template:
    src: knot-resolver/kresd.conf.j2
    dest: /etc/knot-resolver/kresd.conf
    owner: root
    group: knot-resolver
    mode: "0640"
  notify: Start Knot Resolver

- name: Copy dns UFW rules
  ansible.builtin.copy:
    src: ufw/dns
    dest: /etc/ufw/applications.d/dns
    owner: root
    group: root
    mode: "0644"

- name: Allow SSH UFW
  community.general.ufw:
    rule: allow
    app: OpenSSH

- name: Allow DNS UFW
  community.general.ufw:
    rule: allow
    app: DNS

- name: Enable UFW
  community.general.ufw:
    default: deny
    state: enabled
