- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted

- name: Apply netplan
  ansible.builtin.shell: |
    netplan apply
  changed_when: true
