- name: Setup KnotDNS
  gather_facts: true
  become: true
  hosts: knotdns
  roles:
    - role: knotdns

- name: Setup KnotRes
  gather_facts: true
  become: true
  hosts: knotres
  roles:
    - role: knotres

- name: Setup Nginx
  gather_facts: true
  become: true
  hosts: nginx
  roles:
    - role: nginx

- name: Setup Client
  gather_facts: true
  become: true
  hosts: client
  roles:
    - role: client
